### ISSUE TITLE
upgrade canvas to v2.0.0

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/react-d3-cloud#104]
wait for https://github.com/jsdom/jsdom/pull/1964

**Comment by tw0517tw** [comment]
jsdom has released v13.0.0 which supports canvas v2.0

**Comment by tw0517tw** [comment]
now we need to wait `jest-environment-jsdom` update their jsdom deps version

**Comment by tw0517tw** [comment]
It seems that `jest` is not going to update `jsdom` for node 6 compatibility. We should create our own environment as the PR below says or we have to wait node 6 support ends.

https://github.com/facebook/jest/pull/7122
