### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-d3-cloud - Not found

### ISSUE THREAD

**Issue by hothdung** [Yoctol/react-d3-cloud#117]
Hello, 

I am using your package to create a wordcloud, but I also want to modify it in terms of font weight, colors, and adding tooltips. But the WordCloud.js when I modify it, it has no effect on the application. For some reason it cannot be linked with the project. 

when I run this comman: npm install @types/react-d3-cloud

I get these errors:

https://imgur.com/RlYDAhd

https://imgur.com/8MIiLUF

https://imgur.com/nXWBo86

I hope you can answer me soon. Thank you very much.

**Comment by chentsulin** [comment]
This project is not written with TypeScript and don't have a type package in DefinitelyTyped repo, so it's expected behavior.

You could write some custom types in your project or submit the types to the https://github.com/DefinitelyTyped/DefinitelyTyped repo.
