### ISSUE TITLE
Question: How to make it render using 100% width/height of the container?

### ISSUE THREAD

**Issue by carlosalvidrez** [Yoctol/react-d3-cloud#120]
How to make it render using 100% width/height of the container?
Trying to figure out how to make it responsive to screen width changes for example.

PS. Thank you for sharing this library!

**Comment by chentsulin** [comment]
`viewBox` solves this problem perfectly. Just update to the latest version.

**Comment by kongmengfei** [comment]
> `viewBox` solves this problem perfectly. Just update to the latest version.

how to use view box?

**Comment by carlosalvidrez** [comment]
I also have no idea what the solution using "viewBox" looks like @kongmengfei.
@chentsulin could you please provide an example?
Thanks
