### ISSUE TITLE
Request to replace the call to "componentWillMount" (React deprecation warning)

### ISSUE THREAD

**Issue by carlosalvidrez** [Yoctol/react-d3-cloud#121]
This is the warning message: 
`Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: WordCloud`

**Comment by chentsulin** [comment]
`v0.8.0` has been rewritten with React Hooks, so this isn't an issue anymore.
