### ISSUE TITLE
need example

### ISSUE THREAD

**Issue by stegben** [Yoctol/react-d3-cloud#29]
There should be a responsive example.

**Comment by rozzzly** [comment]
> There should be an example.*
FIFY

Also that example should be hosted. If it requires me to clone the project, I'm 10000x more likely to leave the repo and never come back.

**Comment by stegben** [comment]
Sure, it will be hosted by gh-pages

**Comment by stegben** [comment]
You would like to take a look at one example.
https://github.com/Yoctol/react-d3-cloud/issues/33

**Comment by stegben** [comment]
However, it's still not stable. Please wait untill 0.3.0 released, which might happened in a few days
