### ISSUE TITLE
Regenerating the cloud adds new SVGs

### ISSUE THREAD

**Issue by paulpdaniels** [Yoctol/react-d3-cloud#56]
There is a bug currently if the word props are updated and the cloud is re-rendered. The system keeps adding new `svg` elements instead of updating the existing one.

The code [here](https://github.com/Yoctol/react-d3-cloud/blob/master/src/WordCloud.js#L64-L65) seems to be the issue. If you insert a `d3.select('svg').remove()` right before it, it seems to fix the issue.

I can submit a PR to that effect unless there is a more performant way to do this.

**Comment by stegben** [comment]
Thanks for reporting this bug. Any PR is highly welcome!

As for the issue,  `d3.select('svg').remove()` might remove the wrong element if there are other svg elements in the document. A more stable way might be `d3.select(this.wordCloud).selectAll("*").remove();`. This line can be inserted [here](https://github.com/Yoctol/react-d3-cloud/blob/master/src/WordCloud.js#L55), or put it into the `ComponentWillUpdate` method.

**Comment by stegben** [comment]
@paulpdaniels I just fixed the bug and release 0.4.0 on npm. Please re-install the package and have a try :)
