### ISSUE TITLE
Font family does not work.

### ISSUE THREAD

**Issue by shankara403** [Yoctol/react-d3-cloud#86]
The word object returns the font correctly. For example: `word.font` is set to the prop value. But for some reason, the d3 font-family remains the default `Impact` and does not change what so ever.

**Comment by stegben** [comment]
I'll take look at this issue, thanks for posting

**Comment by chentsulin** [comment]
<img width="1066" alt="截圖 2021-08-25 上午10 46 24" src="https://user-images.githubusercontent.com/3382565/130831449-3571e787-630f-4144-9ad4-f65bdc3c2c8c.png">
<img width="1065" alt="截圖 2021-08-25 上午10 45 24" src="https://user-images.githubusercontent.com/3382565/130831464-1c530d82-def0-4dfd-ba10-68db71f2e208.png">

It works just fine in my latest try.
